### ISSUE TITLE
support for Dockerfile

### ISSUE THREAD

**Issue by sandys** [nanobox-io/nanobox#39] opened 2015-11-18 13:56 UTC
Nanobox seems interesting...

I have a Dockerfile that I use to run my production. This is already built.
Is there anything I can use to build a local dev environment quickly using the Dockerfile?  Obviously I can use docker, but quite often new developers have trouble with docker.

It seems to me that Nanobox uses something called Boxfile - but if it is able to ingest Dockerfiles, it would be a killer feature to test Dockerfiles and write code.

**Comment by lyondhill** [comment] 2015-11-20 22:58
@sandys Seems like a good idea. I think we could write a Dockerfile -> Boxfile converter. As well as a Procfile -> Boxfile converter for heroku users

**Comment by sandys** [comment] 2015-11-21 05:11
Please remember that my Dockerfile will remain primary , since my
production deployment happens through Docker. If you could read the
Dockerfile on the fly, that would be a killer feature.

That would essentially mean I can take almost any Dockerfile and create a
nanobox to hack on it!!

**Comment by tylerflint** [comment] 2015-12-10 22:40
This is an interesting consideration. Initially, it appears that @sandys has a misconception about what nanobox is. That said, I think I understand why @sandys perceived nanobox in that way, and I think it would make for a killer project!

A Dockerfile is limited in scope to the configuration of a single docker container. A Boxfile is configuration for an app as a whole, where the configuration never gets to the granular level that a Dockerfile would. The Boxfile is for configuring an app's services, like redis or postgres, and how to build and run the app. Nanobox will take those instructions and compose services of various docker containers (which were previously build with a Dockerfile and hosted on docker hub). Thus, the scope of a Boxfile is at an app-level, and the scope of a Dockerfile is at a container level. They are inherently incompatible by scope.

Nanobox is not a tool to manage docker containers or develop docker containers. Rather, nanobox is a tool designed to eliminate environment setup for application developers. It's really more of a tool for application developers who are intentionally trying to offload the environment setup and configuration. To take the point one step further, it is by design that the users of nanobox will never see or have to be concerned with the underlying docker containers at any point. 

What is being alluded to in this issue, is a different project altogether. That project might be a small nanobox-like tool that would/could launch a vm, build a docker container from a Docker file inside the vm (or a bunch of them from a swarm configuration), mount source from the host into the container, and drop you into a console session. It's likely that this project could use much of the same components, processes, and code from nanobox. Of course, the goals and intended audience for this would be devops, container developers, or app developers who have to run their code on a pre-defined docker infrastructure. This would be pretty darn cool!

I'll need to close this issue as it's not really within the scope of nanobox. However, if you or anyone else is really interested in seeing a project like this, I'd welcome you to discuss this further in the #nanobox irc. If there is enough interest, perhaps we could start a separate project within the nanopack organization.

Thanks for your interest!

**Closed by tylerflint** 2015-12-10 22:40 UTC
Labels: enhancement
