### ISSUE TITLE
Enhance installation docs

### ISSUE THREAD

**Issue by saun4app** [nanobox-io/nanobox#497] opened 2017-07-18 21:05 UTC
When download and installed `nanobox` for the *first time*, the instruction says (with good intention) to use `nanobox run`.  After playing with `nanobox` a little bit, I can see that `nanobox` is a friend what you use often. The `nanobox` team wants you to get to know `nanobox run` early.

However, running `nanobox run` for the *first time*, a error message says something like this appears: `boxfile.yml` is missing.  I (a first-time user) took the error message to indicate the `nanobox instalation` was *not entirely successful*.  I want to sure if I should go on or re-install. I re-install multiple times.

@sanderson from nanobox helped me to understand that `nanobox configure` work for first-time installation (same as `nanobox run`), and does not show a missing `boxfile.yml` message. 

Therefore, I would like to suggest changing the first-time instllation instruction to us `nanobox configure`, instead of `nanobox run`, to ensure an early success experience.  

It would be helpful is the instructions is something like this:
```
nanobox configure
nanobox version
```

- Install nanobox
- Seeing the version means successful installation

Now we can go on to crating a simple `nanobox` app.

**Comment by lyondhill** [comment] 2017-07-19 19:53
Thanks for the feedback. Nanobox can be run in the way you mentioned `nanobox configure` then `nanobox run`. It was designed to be flexible in that way. The instructions were written to only have the `nanobox run` command intentionally because it help to convey that nanobox is a tool made for productivity and we didn't wont new users to get bogged down in configuration and setup. If there is more interest in the community to modify the structure we will definitely re evaluate.

**Comment by sanderson** [comment] 2017-07-19 19:57
@saun4app I also pushed an update to the install docs that hopefully help to clarify. You can view them here: https://docs.nanobox.io/install/

I think one thing we do need to consider from your feedback is the gap between installing nanobox and using nanobox. [The guides](https://guides.nanobox.io) are designed to fill this gap, but maybe we're not doing a good enough job of funneling people there or clearly communicating the process.

**Comment by saun4app** [comment] 2017-07-19 19:59
@lyondhill,  thanks for the response.  As I mentioned, I believe using `nanobox run` was based on good intention.  However, the good causes unintended negative consequence.   In order to actualize your good intention, a new user either 

1) has to learn nanobox app creation before installing nanobox, or.   
2) get an error message implies that the installation has failed.

**Comment by saun4app** [comment] 2017-07-19 20:01
@anderson,  thanks for you quick action as always.  I am not seeing step-by-step instructions for install on https://docs.nanobox.io/install/; not even clearing cache?

**Comment by saun4app** [comment] 2017-07-19 20:16
@sanderson,

I would be helpful to change the label of "Guides" to something like "App Development Guides", "Creating nanobox Apps", etc.  The current label "Guides" under "GETTING STARTED"  implies that the "Guide includes nanobox installation.   

The [Install Nanobox](https://docs.nanobox.io/install/) pages more than implying it has step-by-step instruction for installing nanobox, but I did not find it.

**Comment by glinton** [comment] 2017-08-29 15:02
@saun4app, do you mind providing something you'd like to see for "full step-by-step" instructions for installing. It does seem like it could benefit that install nanobox page you linked.

**Comment by saun4app** [comment] 2017-08-29 15:15
## Setup Nanobox

This guide walks you through the process of downloading and installing Nanobox VM and CLI on your local machine.


## Sign Up and Download at `nanobox.io`

 - `nanobox.io` allows [local development for free](https://nanobox.io/pricing). However, only registered users are allowed to download `nanobox`.
 - Register with `nanobox.io` at https://dashboard.nanobox.io/users/register.
 - Download the appropriate version of `nanobox` for your `local machine`.
 - Register at [nanoboxio.slack.com](https://nanoboxio.slack.com) by following the instruction on the welcome email from `nanaobox.io`.
## Installing `nanobox`

 - To instal `nanobox` for Ubuntu, run the following commands at the download directory
```bash
docker -v
dpkg -i nanobox_2_amd64.deb
nanobox configure
nanobox version
```


 - Get help at [nanoboxio.slack.com](https://nanoboxio.slack.com) if you encounter errors.
## Checking `local machine`

 - Run the following `bash` commands to verify *local machine* setup is ready for creating `nanobox` app
```bash
docker -v
node -v
npm -v
nanobox version
```


 - Get help at [nanoboxio.slack.com](https://nanoboxio.slack.com) if you encounter errors with `nanobox version`.

**Comment by glinton** [comment] 2017-08-29 20:26
Thank you for the suggestion. However, there are some issues with your instructions: 
#### Installing nanobox
* `docker -v` isn't *required* to run in order to install nanobox. (it is *possible* that it is a pre-requisite though, depending on what the user wants to do (native|vbox))
* `dpkg -i` isn't required as all os installers can be double clicked (a common method of running, as our docs direct)
* `nanobox version` isn't required to complete the installation or anything.

#### Checking `local machine`
* again `docker` isn't a hard requirement
* `node` and `npm` don't need be on your local machine for nanobox to run, all you need is the nanobox binary, docker or virtualbox, and an editor.
* `nanobox version` will only print the version, no checking is involved anymore.

Really, what could be helpful to users would be adding `nanobox configure` and `nanobox start` to the install doc. I'm going to close this issue and tag @sanderson, since he is over the docs.

Thanks again for the feedback/suggestion though.

**Closed by glinton** 2017-08-29 20:26 UTC
Labels: docs, waiting for info
