### ISSUE TITLE
Unable to run 'nanobox dev'.

### ISSUE THREAD

**Issue by gabovanlugo** [nanobox-io/nanobox#148] opened 2016-04-12 16:57 UTC
Hey there! I have some trouble trying to setup nanobox on my project. I've already looked to another similar issues but nothing of that helps.

I've downloaded nanobox with and without Vagrant and VirtualBox.
I've cloned my repo from a remote server.
Execute 'nanobox dev', on my root project folder. Everything seems to install correctly, I type my password and for some reason I'm having the same error.

This my terminal output:

```

➜  site-frontend git:(master) nanobox dev
+> Creating /Users/Gabo/.nanobox directory
+> Installing nanobox/boot2docker...
   [***************************************   99%] 192k/s (0:00:01 remaining))
+> Creating a nanobox
+> Nanobox may require admin privileges to modify your /etc/hosts and /etc/exports files.
Password:

   - Importing nanobox base image....
   - Booting virtual machine........
   - Configuring virtual network.........................A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)
A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)
A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)
A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)
A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)
A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)
A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)
A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)
A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)
A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)
A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)
A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)
A vagrant error occured (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details)

A fatal Vagrant error occurred (See /Users/Gabo/.nanobox/apps/site-frontend/vagrant.log for details). Exiting...%

```

Then, of course, I go the log file and this is what it looks like:

```
2016-04-12 10:45:06 INFO  Bringing machine 'site-frontend' up with 'virtualbox' provider...
2016-04-12 10:45:06 INFO  ==> site-frontend: Importing base box 'nanobox/boot2docker'...
2016-04-12 10:45:07 INFO  2016-04-12 10:45:08 INFO  [KProgress: 10%!(NOVERB)
2016-04-12 10:45:08 INFO  [KProgress: 20%!(NOVERB)
2016-04-12 10:45:09 INFO  [KProgress: 30%!(NOVERB)
2016-04-12 10:45:10 INFO  [KProgress: 40%!(NOVERB)
2016-04-12 10:45:10 INFO  [KProgress: 90%!(NOVERB)
2016-04-12 10:45:10 INFO  [K==> site-frontend: Matching MAC address for NAT networking...
2016-04-12 10:45:10 INFO  ==> site-frontend: Checking if box 'nanobox/boot2docker' is up to date...
2016-04-12 10:45:12 INFO  ==> site-frontend: Setting the name of the VM: site-frontend
2016-04-12 10:45:13 INFO  ==> site-frontend: Clearing any previously set network interfaces...
2016-04-12 10:45:13 INFO  ==> site-frontend: Preparing network interfaces based on configuration...
2016-04-12 10:45:13 INFO  site-frontend: Adapter 1: nat
2016-04-12 10:45:13 INFO  site-frontend: Adapter 2: hostonly
2016-04-12 10:45:13 INFO  ==> site-frontend: Forwarding ports...
2016-04-12 10:45:13 INFO  site-frontend: 22 (guest) => 12047 (host) (adapter 1)
2016-04-12 10:45:13 INFO  ==> site-frontend: Running 'pre-boot' VM customizations...
2016-04-12 10:45:13 INFO  ==> site-frontend: Booting VM...
2016-04-12 10:45:14 INFO  ==> site-frontend: Waiting for machine to boot. This may take a few minutes...
2016-04-12 10:45:14 INFO  site-frontend: SSH address: 127.0.0.1:12047
2016-04-12 10:45:14 INFO  site-frontend: SSH username: docker
2016-04-12 10:45:14 INFO  site-frontend: SSH auth method: password
2016-04-12 10:45:36 INFO  site-frontend:
2016-04-12 10:45:36 INFO  site-frontend: Inserting generated public key within guest...
2016-04-12 10:45:36 INFO  site-frontend: Removing insecure key from the guest if it's present...
2016-04-12 10:45:36 INFO  site-frontend: Key inserted! Disconnecting and reconnecting using new SSH key...
2016-04-12 10:45:37 INFO  ==> site-frontend: Machine booted and ready!
2016-04-12 10:45:37 INFO  ==> site-frontend: Checking for guest additions in VM...
2016-04-12 10:45:37 INFO  ==> site-frontend: Configuring and enabling network interfaces...
2016-04-12 10:45:37 INFO  ==> site-frontend: Exporting NFS shared folders...
2016-04-12 10:45:37 INFO  ==> site-frontend: Preparing to edit /etc/exports. Administrator privileges will be required...
2016-04-12 10:45:38 INFO  The nfsd service does not appear to be running.
2016-04-12 10:45:38 INFO  Starting the nfsd service
2016-04-12 10:45:38 INFO  ==> site-frontend: Mounting NFS shared folders...
2016-04-12 11:07:13 ERROR The following SSH command responded with a non-zero exit status.
2016-04-12 11:07:13 ERROR Vagrant assumes that this means the command failed!
2016-04-12 11:07:13 ERROR 2016-04-12 11:07:13 ERROR mount -o 'nfsvers=3,proto=tcp' 172.16.7.1:'/Users/Gabo/Projects/site-frontend' /vagrant/code/site-frontend
2016-04-12 11:07:13 ERROR 2016-04-12 11:07:13 ERROR Stdout from the command:
2016-04-12 11:07:13 ERROR 2016-04-12 11:07:13 ERROR 2016-04-12 11:07:13 ERROR 2016-04-12 11:07:13 ERROR Stderr from the command:
2016-04-12 11:07:13 ERROR 2016-04-12 11:07:13 ERROR mount: RPC: Authentication error; why = Client credential too weak
2016-04-12 11:07:13 ERROR mount: mounting 172.16.7.1:/Users/Gabo/Projects/site-frontend on /vagrant/code/site-frontend failed: Bad file descriptor
2016-04-12 11:07:13 FATAL [commands/create] vagrant.Up() failed - exit status 1
2016-04-12 11:07:13 *LOG* Closing log now
```

- I've tried on two different clean install machines.
- I've already tried by downloading Vagrant and VirtualBox using standalone installers.
- I've Mac OS X El Capitan 10.11.4 in both machines.
- Considering that it is a Vagrant error, I've tried to setup a Vagrant Box successfully using other image. So, I don't think Vagrant it's not installed correctly.

Any advice on that matter?

Thanks in advance.

**Comment by tylerflint** [comment] 2016-04-12 22:11
It looks like the issue is specifically trying to mount the shared volumes via NFS. Nanobox can be configured to use VirtualBox's native driver instead. 

@sdomino Can you please provide a reference within the .nanofile where this can be accomplished?

**Comment by amacgregor** [comment] 2016-05-23 23:43
@tylerflint @gabovanlugo I had a similar problem today, in this case was due to a conflict in the nfs /etc/exports file. Try running the following to check if there is an issue:

`sudo nfsd checkexports`

**Comment by tylerflint** [comment] 2016-10-13 18:29
Just a heads up, there has been some progress on this. Nanobox has been completely re-written from the ground up, and we just released the v1 into beta this week. Nanobox no longer depends on Vagrant, and so this is likely not an issue anymore. We would love to get your feedback on the new version. The new guides are still a WIP but should be usable within the next week. If you're interested, we'd love to talk with you on irc #nanobox or we can bring you into our slack channel as well.

Additionally, Nanobox and Nanobox Cloud have been merged into a unified process. If you would be interested in early access to the private beta please let me know and I can get you an access token.

Just reach out to hello@nanobox.io and we can get you going.

I really appreciate both of your help on this. I'll go ahead and close this ticket and hope to hear from you directly.

**Closed by tylerflint** 2016-10-13 18:29 UTC
